### ISSUE TITLE
Question about the distorsion coefficient in the yml file

### ISSUE THREAD

**Issue by PotatoDroid5** [MRPT/mrpt#1225]
Hello, I need to convert the intrinsic parameters from .yml to .cam format. Just to be sure, in the yml file generated:

```
camera_matrix:
  cols: 3
  data: [652.3032180347936, 0, 324.1105454718237, 0, 647.8789451143271, 235.0098017548972, 0, 0, 1]
  rows: 3
camera_name: camera1
distortion_coefficients:
  cols: 8
  data: [-0.1497031993890412, 1.362350091825391, 0.003514720345557172, 0.008293638896066356, -3.412437392789501, 0, 0, 0]
  rows: 1
```

is it equivalent to:
```
  <focallength x="652.3032180347936" y="647.8789451143271" />
  <principalpoint x="324.1105454718237" y="235.0098017548972" />
  <distortion k1="-0.1497031993890412" k2="1.362350091825391" k3="0.003514720345557172" p1="0.008293638896066356" p2="-3.412437392789501" />
```

or is the order of the distortion coefficients different?
